services:
  agenda-gremio-alert:
    build:
      context: .
      dockerfile: Dockerfile
    image: agenda-gremio-alert:local
    ports:
      - "9000:8080"
    environment:
      SENDER_EMAIL: ${SENDER_EMAIL:-sender@example.com}
      RECIPIENT_EMAIL: ${RECIPIENT_EMAIL:-recipient@example.com}
